import type { WatchAts } from "@/types/job-search";

export const SUGGESTED_WATCHLIST: { name: string; ats: WatchAts; token: string }[] = [
  { name: "Airbnb", ats: "greenhouse", token: "airbnb" },
  { name: "Anthropic", ats: "ashby", token: "anthropic" },
  { name: "Asana", ats: "greenhouse", token: "asana" },
  { name: "Automattic", ats: "greenhouse", token: "automattic" },
  { name: "Cloudflare", ats: "greenhouse", token: "cloudflare" },
  { name: "Datadog", ats: "greenhouse", token: "datadog" },
  { name: "Discord", ats: "greenhouse", token: "discord" },
  { name: "Dropbox", ats: "greenhouse", token: "dropbox" },
  { name: "Figma", ats: "greenhouse", token: "figma" },
  { name: "GitHub", ats: "greenhouse", token: "github" },
  { name: "GitLab", ats: "greenhouse", token: "gitlab" },
  { name: "Linear", ats: "ashby", token: "linear" },
  { name: "Notion", ats: "ashby", token: "notion" },
  { name: "OpenAI", ats: "ashby", token: "openai" },
  { name: "Plaid", ats: "greenhouse", token: "plaid" },
  { name: "Ramp", ats: "ashby", token: "ramp" },
  { name: "Reddit", ats: "greenhouse", token: "reddit" },
  { name: "Rippling", ats: "ashby", token: "rippling" },
  { name: "Shopify", ats: "greenhouse", token: "shopify" },
  { name: "Spotify", ats: "lever", token: "spotify" },
  { name: "Stripe", ats: "greenhouse", token: "stripe" },
  { name: "Vercel", ats: "ashby", token: "vercel" },
  { name: "Webflow", ats: "greenhouse", token: "webflow" },
  { name: "Zapier", ats: "greenhouse", token: "zapier" },
];
